config/routes.rb
IdleCampus::Application.routes.draw do
  
  use_doorkeeper
#   devise_scope :user do

# # get 'student/sign_up' => 'registrations#new', :user => { :user_type => 'student' }
# # get 'teacher/sign_up' => 'registrations#new', :user => { :user_type => 'teacher' }
# # get "users/sign_up" =>  redirect("/student/sign_up")
#  get "users/sign_up" => 'registrations#new', :user => { :user_type => 'teacher' }
# end
  devise_for :users,:controllers => {:sessions => 'sessions',:registrations => "registrations",omniauth_callbacks: "users/omniauth_callbacks"}
  resources :posts,only: [:index]
  get "password_resets/new"
  get "push/create"
  resources :password_resets
  match "checkEmail" => "user_validations#checkEmail",via: 'get'
  match "checkName" => "user_validations#checkName",via: 'get'
  resource :dashboard,only: [:show]
  post "users/frommobile"
  post "users/login"
  post "users/send_push"

  resources :users,except: :index,  :constraints => { :id => /[^\/]+/ }
  resource :home, only: :show
  resources :groups do
    resource :timetable,only: [:create,:show]
    resources :notes
    resources :files,only: :index
  end


    namespace :api do
    namespace :v1 do
      resources :profiles
      resources :users
      get '/me' => "credentials#me"
      get '/fast' => 'fast#index'
    end
  end
  
  # resources :teachers
  # resources :students
  
  resource :push,only: :create
 
  resources :notes
  resources :alerts, only: [:new, :create]
  namespace :api do
    resources :users,only: :create
    resources :groups,only: :show
  end
  root  'homes#show'
 
 
  match '/about',to: "static_pages#about",via: :get
  resources :messages, only: [:new, :create]
  match 'contact' => 'contact#new', :via => :get
  match 'contact' => 'contact#create',:via => :post
  
  
  namespace :api do
    resources :users, only: [:create]
  end
  
  resources :password_resets
  
end

app/models/group.rb
#
class Group < ActiveRecord::Base
  has_many :folders
  validates :name, presence: true
  has_one :timetable
  has_many :timetable_fields
  belongs_to :user
  has_many :teachers
  has_many :subjects
  has_many :rooms
  has_many :alerts, -> { order('created_at desc')}
  has_many :notes
  has_many :posts
  has_many :files, through: :notes
  has_many :students
  belongs_to :teacher
  has_many :followers, class_name: 'Student'
  belongs_to :creator, class_name: 'Teacher', foreign_key: 'teacher_id'
  acts_as_followable
  
  before_create :set_group_code


  def get_field_entries
    field_entries = [
                      FieldEntry.new("room",rooms.pluck(:name)).to_hash,
                      FieldEntry.new("teacher",teachers.pluck(:name)).to_hash,
                      FieldEntry.new("subject",subjects.pluck(:name)).to_hash
                    ]
  end
  
  def set_group_code
   self.group_code = Group.get_group_code
  end

  def self.find_group(id)
    Group.find_by_group_code(id) || Group.find(id)
  end

  def get_users
    res = []
    
    members = self.followers
    members = members.map do |member|
      index = member.jabber_id.index('/')
      if !index.nil?
        member.jabber_id.slice(0..index - 1)
      else
        member.jabber_id
      end
      
    end
    return members
  end

  def self.get_group_code
    new_group_code = generate_group_code
    while Group.exists?(group_code: new_group_code)
      new_group_code = generate_group_code
    end
    new_group_code
  end

  def create_post(item)
    post = posts.new
    post.targetable = item
    post.save
    post
  end

  # Generates a random string from a set of easily readable characters
  def self.generate_group_code(size = 6)
    charset = %w{ 2 3 4 6 7 9 A C D E F G H J K M N P Q R T V W X Y Z}
    (0...size).map { charset.to_a[rand(charset.size)] }.join
  end

  def to_hash
    group = {}
    group[:name] = name
    group[:code] = group_code
    group
  end
end

app/controllers/api/groups_controller.rb
class Api::GroupsController < ApplicationController
	respond_to :json
  def show
    @group = Group.find_by_group_code(params[:id])
   
    if @group
     render :json => @group
   else 
     render text: "group not found"
   end
  end   
end

app/controllers/groups_controller.rb
require 'json'
require 'xmpp4r'
require 'xmpp4r/pubsub'
require 'xmpp4r/pubsub/helper/servicehelper.rb'
require 'xmpp4r/pubsub/helper/nodebrowser.rb'
require 'xmpp4r/pubsub/helper/nodehelper.rb'
# GroupsController.rb
class GroupsController < ApplicationController
  respond_to :json, :html
  before_filter :authenticate_user!, only: [:create, :destroy,:show]
  def index
    @groups = current_user.groups
    respond_with @groups
  end

  def show
    @group = Group.find(params[:id])
    gon.a = ""
    @posts = @group.alerts.includes(:group) + @group.notes.includes(:group)
    @posts = @posts.sort_by(&:created_at).reverse
      # @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(5)
  end

  def new
    @group = Group.new
    @group.group_code = Group.get_group_code
  end

  def create
    @group = current_user.groups.build(name:params[:group][:name])
    # @group.group_code = Group.get_group_code
    
    @group.save
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    xmpp = DRbObject.new_with_uri 'druby://localhost:7777'
    @group = current_user.groups.build
    @group.name = params[:group][:name]
    @group.group_code = Group.get_group_code
    xmpp.create_group(@group.group_code)
    if @group.save
      puts @group.group_code
    else
      render 'static_pages/home'
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    flash[:notice] = 'Successfully destroyed group.'
    redirect_to galleries_url
  end
end

app/views/groups/_group.html.erb
	<li><%= link_to "<i class='fa fa-inbox'></i>            #{group.name}".html_safe,group_path(group) %></a></li>

app/views/groups/_header.html.erb
<div class="widget" class="span3">

	<div class="widget-content">
    <%=  gravatar_for(current_user, size: 52) %>

    <table>
      <tr>
     <td>Group Name:</td> 
    <td>  <button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="right" id="groupname" title="" data-original-title=""><%= @group.name%></button></td>
  </tr>
  <tr>
   <td>   <% if current_user.rolable_type == "Teacher"%>
      Group ID:</td><td> <button type="button" class="btn btn-default" data-toggle="tooltip" data-placement="bottom" id="groupcode" title="" data-original-title="Pass this group code to your students to follow"  data-intro="Pass this group code to your students to follow" data-position="top"><%= @group.group_code%></button></td>
<% else %>
      Group ID: <button type="button" class="btn btn-default" id="groupcode"><%= @group.group_code%></button>
<% end %>
</tr>
    </table>
	</div>
</div>

app/views/groups/_options.html.erb
<ul class="nav nav-pills nav-stacked">
  <li data-intro="See what files have been uploaded" data-position="right"><%= link_to '<i class="icon-file icon-white"></i> Files'.html_safe,group_files_path(@group),style:"background: #49708A;
    color: white;"%></li>
    
    <li data-intro="Edit or view the timetable for the group" data-position="right"><%= link_to  '<i class="icon-calendar icon-white"></i> Timetable'.html_safe,group_timetable_path(@group.group_code),style:"background: #49708A;
      color: white;"%></li>
</ul>

app/views/groups/create.js.erb
$("#sidebar").append("<%= escape_javascript(render(@group)) %>") 
$('#group_name').val('');
$("abbr.timeago").timeago();
group_code = "<%= escape_javascript(@group.group_code) %>";

app/views/groups/index.html.erb
<% @groups.each do |group| %>
  <%= link_to group.name,group %>
  <%= group.group_code %>
  <% end %> 

app/views/groups/new.html.erb
<%= form_for @group do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>


<div ng-controller="GroupsCtrl">
	<div class="row">
	  <div class="span6 offset3">
    <form class="form-inline">
        <input class="create-group-input span2" placeholder="Group Name" type="text"
               id="creategroupinput" ng-model="data.creategroup"/>

        <button data-dismiss="modal" class="btn btn-primary" id="creategroupbutton"
                ng-click="createGroup()">Create
        </button>
		<!-- <button ng-click="getGroupsCreated()">Get Created Groups</button> -->
		
    </form>
 
</div>
</div>
</div>

app/views/groups/show.html.erb
<div class="row" ng-controller="GroupsCtrl" ng-init="get()" style="margin-top:5%">
    <aside class="col-md-3">
        <section>
            <div>
              
           

                <%= render 'groups/header' %>
                
                   <%= render 'groups/options'%>

                <% if current_user.rolable_type == "Teacher" %>
                    <section>
                        <%= render 'shared/group_form' %>
                    </section>
                    <section>
                        <%= render 'shared/groups' %>
                    </section>

                <% end %>


            </div>
        </section>

    </aside>
    <div class="col-md-5">
        <!-- Main content         -->
        <div id="main-content">
            <!-- Container -->
            <div class="container">
                <% if current_user.rolable_type == "Teacher" %>

                    <%= render 'messages/tabs' %>


                <% end %>




                <div class="col-md-10">
                    <h1 class="page-title">Group Posts</h1>
                    <!-- <div class="alert alert-danger">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
                      This is a sample <strong>alert message</strong>. You can close it at any time.
                    </div> -->

                    <div class="widget">
                        <div class="widget-header">
                            <h3><i class="icon-comments"></i>&nbsp;&nbsp;Posts</h3>
                        </div>
                        <div class="widget-content">
                            <ul class="messages-activity" id="posts">
                              
                              
                              <%= render @posts%>
                            
                           


                            </ul>
                        </div>
                    </div>

                </div>


            </div>
        </div>


        <!-- /Content -->


        <!-- /Content -->
    </div>


</div>
<!-- /Container -->
</div>




</div>

app/views/groups/update.js.erb
$("#sidebar").append("<%= escape_javascript(render(@group)) %>") 