config/routes.rb
IdleCampus::Application.routes.draw do
  
  use_doorkeeper
#   devise_scope :user do

# # get 'student/sign_up' => 'registrations#new', :user => { :user_type => 'student' }
# # get 'teacher/sign_up' => 'registrations#new', :user => { :user_type => 'teacher' }
# # get "users/sign_up" =>  redirect("/student/sign_up")
#  get "users/sign_up" => 'registrations#new', :user => { :user_type => 'teacher' }
# end
  devise_for :users,:controllers => {:sessions => 'sessions',:registrations => "registrations",omniauth_callbacks: "users/omniauth_callbacks"}
  resources :posts,only: [:index]
  get "password_resets/new"
  get "push/create"
  resources :password_resets
  match "checkEmail" => "user_validations#checkEmail",via: 'get'
  match "checkName" => "user_validations#checkName",via: 'get'
  resource :dashboard,only: [:show]
  post "users/frommobile"
  post "users/login"
  post "users/send_push"

  resources :users,except: :index,  :constraints => { :id => /[^\/]+/ }
  resource :home, only: :show
  resources :groups do
    resource :timetable,only: [:create,:show]
    resources :notes
    resources :files,only: :index
  end


    namespace :api do
    namespace :v1 do
      resources :profiles
      resources :users
      get '/me' => "credentials#me"
      get '/fast' => 'fast#index'
    end
  end
  
  # resources :teachers
  # resources :students
  
  resource :push,only: :create
 
  resources :notes
  resources :alerts, only: [:new, :create]
  namespace :api do
    resources :users,only: :create
    resources :groups,only: :show
  end
  root  'homes#show'
 
 
  match '/about',to: "static_pages#about",via: :get
  resources :messages, only: [:new, :create]
  match 'contact' => 'contact#new', :via => :get
  match 'contact' => 'contact#create',:via => :post
  
  
  namespace :api do
    resources :users, only: [:create]
  end
  
  resources :password_resets
  
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      redirect_to(root_path, :notice => "Message was successfully sent.")
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end

end

app/views/contact/new.html.erb
<% provide(:header,"<h2>Contact Us<span class='tblue'>.</span></h2>".html_safe)%>

<div class="container">
  <div class="row">
    <div class="col-md-4">
    <h3>Drop me a line!</h3>
    <hr>
    <address>
    <strong>Email:</strong> <a href="mailto:#"> ankothari@idlecampus.com</a><br><br>
    <strong>Phone:</strong> +91 9869000688
    </address>
    </div>
    
    <div class="col-md-8 contact-form">
      <%= form_for @message, :url => contact_path do |form| %>
        <div class="row">
          <div class="col-md-6 form-group">
             <%= form.text_field :name,placeholder:"Name",autofocus: true,required: true,class:"form-control col-md-12" %>
          </div>
          <div class="col-md-6 form-group">
             <%= form.email_field :email,placeholder:"Email",required: true,class:"form-control col-md-12" %>
         
          </div>
          <%= form.hidden_field :subject,value:"New Message"%>
        </div>
        <div class="form-group">
          <%= form.text_area :body,placeholder:"Message",rows:5,class:"col-md-8 form-control" %>
        </div>
        
        <p>
        <%= form.submit "Submit",class:"btn btn-primary",style:"margin-top:20px;" %>
        </p>
      
      <% end %>
    </div>
  </div>
</div>